baseURL: https://stanleyyu.io
languageCode: en-us
title: stanleyyu.io

params:
  AuthorName: Stanley Yu
  GitHubUser: stanley98yu

defaultContentLanguage: en
metaDataFormat: yaml
publishDir: site

disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS
  - robotsTXT
  - 404
  - sitemap