baseURL: https://stanleyyu.io
languageCode: en-us

params:
  title: "Stanley Yu"
  description: "Stanley Yu is a software developer and researcher at Columbia, working on machine learning, distributed systems, and algorithms. He is currently working as a software engineering intern at Butterfly Network."
  author: "Stanley Yu"
  github_username: "stanley98yu"
  twitter_handle: "@stanley98yu"
  google_analytics_id: "UA-123576548-1"
  domain: "stanleyyu.io"
  root: "https://stanleyyu.io"

defaultContentLanguage: en
metaDataFormat: yaml
publishDir: site

verbose: true
disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS
  - robotsTXT
  - 404
  - sitemap