baseURL: https://stanleyyu.io
languageCode: en-us

params:
  title: "Stanley Yu"
  description: "Software Developer & Researcher in New York. Research Assistant at Cornell Tech. CS at Columbia. Feel free to reach out to me to chat!"
  author: "Stanley Yu"
  github_username: "stanley98yu"
  twitter_handle: "@stanley98yu"
  google_analytics_id: "UA-123576548-1"
  domain: "stanleyyu.io"
  root: "https://stanleyyu.io"

defaultContentLanguage: en
metaDataFormat: yaml
publishDir: site

verbose: true
disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS
  - robotsTXT
  - 404
  - sitemap